import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const translations = {
  ko: {
    // 사이트 정보
    siteName: '대전으로',
    siteSubtitle: 'Let\'s Go Daejeon',
    siteDescription: '대전광역시의 아름다운 관광지와 맛집, 축제 정보를 소개합니다.',

    // 네비게이션
    nav: {
      home: '홈',
      travel: '관광지',
      festival: '축제/행사',
      food: '맛집',
      parking: '주차장',
      map: '지도',
      culture: '문화시설',
      medical: '의료',
      shopping: '쇼핑',
      accommodation: '숙박'
    },

    // 퀵메뉴
    quickMenu: {
      title: '완벽한 대전 여행을 위한 서비스',
      subtitle: '대전의 다양한 매력을 카테고리별로 만나보세요',
      travelCourse: '여행코스',
      restaurant: '맛집',
      festival: '축제',
      leisure: '레저',
      seasonTravel: '계절여행',
      recommend: '추천코스'
    },

    // 히어로 섹션
    hero: {
      slide1: {
        title: '대전의 봄',
        subtitle: '벚꽃이 만개한 대전의 봄을 만나보세요',
        description: '유성온천, 한밭수목원에서 펼쳐지는 봄꽃 향연'
      },
      slide2: {
        title: '과학의 도시',
        subtitle: '대한민국 과학수도 대전',
        description: '국립중앙과학관, 대전엑스포과학공원에서 미래를 만나다'
      },
      slide3: {
        title: '맛의 고장',
        subtitle: '대전의 숨겨진 맛집을 찾아서',
        description: '성심당, 두부두루치기... 대전만의 특별한 맛'
      },
      viewMore: '자세히 보기'
    },

    // 인기 관광지
    popularSpots: {
      title: '대전의 인기 관광지',
      subtitle: '가장 많이 찾는 대전의 명소를 소개합니다',
      viewMore: '더 많은 관광지 보기'
    },

    // 여행 코스
    travelCourse: {
      title: '추천 여행 코스',
      subtitle: '테마별로 즐기는 알찬 대전 여행',
      viewCourse: '코스 보기'
    },

    // 축제 섹션
    festivalSection: {
      title: '대전의 축제 · 행사',
      subtitle: '대전에서 펼쳐지는 다채로운 축제를 만나보세요',
      viewAll: '모든 축제 보기',
      upcoming: '예정'
    },

    // 맛집 섹션
    foodSection: {
      title: '대전 맛집 추천',
      subtitle: '대전에서만 맛볼 수 있는 특별한 음식들',
      viewMore: '더 많은 맛집 보기'
    },

    // 푸터
    footer: {
      description: '대전광역시의 아름다운 관광지와 맛집, 축제 정보를 소개합니다. 대전의 숨겨진 매력을 발견해보세요.',
      tourInfo: '관광 정보',
      customerService: '고객 서비스',
      relatedSites: '관련 사이트',
      faq: '자주 묻는 질문',
      tourOffice: '관광 안내소',
      travelGuide: '여행 가이드',
      daejeonCity: '대전광역시',
      visitKorea: '대한민국 구석구석',
      tourCorp: '대전관광공사',
      copyright: '© 2026 대전으로. All rights reserved.',
      privacy: '개인정보처리방침',
      terms: '이용약관',
      copyrightPolicy: '저작권정책',
      tourHotline: '관광안내 1577-3025',
      dataSource: '본 사이트의 관광정보는 대전광역시 공공데이터포털, 한국관광공사 Tour API에서 제공받은 정보입니다.',
      disclaimer: '본 사이트는 대전광역시 공식 홈페이지가 아니며, 관광 정보 제공을 목적으로 운영되는 민간 사이트입니다.'
    },

    // 공통
    common: {
      viewDetails: '자세히 보기',
      category: '카테고리',
      all: '전체',
      total: '총',
      count: '개',
      hours: '시간',
      location: '위치',
      period: '기간',
      search: '검색',
      allDong: '전체 동',
      attractions: '관광지',
      restaurants: '맛집',
      addedToTrip: '여행에 추가되었습니다!',
      addFailed: '추가에 실패했습니다.',
      errorOccurred: '오류가 발생했습니다.',
      syncRequired: '관리자 페이지에서 TourAPI 데이터를 먼저 동기화해주세요.',
      loadFailed: '데이터를 불러오는데 실패했습니다.',
      loadingAttractions: '관광지 정보를 불러오는 중...',
      loadingRestaurants: '맛집 정보를 불러오는 중...',
      loadingFestivals: '축제 정보를 불러오는 중...',
      loadingData: '데이터를 불러오는 중...',
      visitWebsite: '홈페이지 방문',
      addToTrip: '내 여행에 추가',
      noImage: '이미지 없음',
      noDescription: '설명이 없습니다.',
      noResults: '검색 결과가 없습니다.',
      noTrips: '저장된 여행이 없습니다.',
      createTrip: '새 여행 만들기',
      selectTrip: '여행을 선택하세요',
      selectDay: '일차를 선택하세요',
      photoBy: '사진: ',
      sourceBy: '출처: ',
      photoByKTO: '사진 제공: 한국관광공사',
      linkCopied: '링크가 복사되었습니다!',
      loadingTrip: '여행 계획을 불러오는 중...',
      tripNotFound: '여행 계획을 찾을 수 없습니다.',
      backToHome: '홈으로 돌아가기',
      loadingDetails: '상세 정보 로딩 중...',
      getDirections: '카카오맵으로 길찾기',
      noDaysInTrip: '선택한 여행에 일정이 없습니다.',
      addDaysHint: '"나의 여행" 페이지에서 일정을 먼저 추가해주세요.',
      dayFormat: '{n}일차',
      navigate: '길찾기',
      retry: '다시 시도',
      noAddress: '주소 정보 없음'
    },

    // 카테고리
    categories: {
      all: '전체',
      nature: '자연/공원',
      science: '과학/문화',
      spa: '휴양/온천',
      history: '역사/유적',
      experience: '체험/액티비티',
      korean: '한식',
      bakery: '베이커리',
      cafe: '카페',
      western: '양식',
      culture: '문화/과학',
      tradition: '문화/전통',
      food: '음식',
      sports: '스포츠/건강'
    },

    // 페이지 타이틀
    pages: {
      travel: {
        title: '대전 관광지',
        subtitle: '과학의 도시 대전의 다양한 매력을 발견하세요',
        spots: '관광지'
      },
      festival: {
        title: '대전 축제 · 행사',
        subtitle: '대전에서 펼쳐지는 다채로운 축제와 행사를 만나보세요',
        festivals: '축제/행사',
        performances: '문화공연',
        loadingEvents: '공연/행사 정보를 불러오는 중...',
        theme: '테마',
        place: '장소',
        events: '공연/행사',
        noEvents: '현재 진행중인 행사가 없습니다.',
        organizedBy: '주관'
      },
      food: {
        title: '대전 맛집',
        subtitle: '대전에서만 맛볼 수 있는 특별한 음식들을 소개합니다',
        restaurants: '맛집'
      },
      medical: {
        title: '의료기관',
        subtitle: '대전의 병원, 의원, 약국 정보를 확인하세요',
        hospital: '병원',
        clinic: '의원',
        pharmacy: '약국'
      },
      accommodation: {
        title: '숙박',
        subtitle: '대전에서 편안한 휴식을 즐기세요',
        hotel: '호텔',
        motel: '모텔',
        pension: '펜션',
        guesthouse: '게스트하우스'
      },
      culture: {
        title: '문화시설',
        subtitle: '대전의 문화와 예술을 경험하세요',
        museum: '박물관',
        library: '도서관',
        theater: '공연장',
        gallery: '전시관'
      },
      shopping: {
        title: '쇼핑',
        subtitle: '대전의 쇼핑 명소를 둘러보세요',
        loading: '쇼핑 명소를 불러오는 중...',
        noResults: '쇼핑 명소가 없습니다.',
        searchPlaceholder: '쇼핑 명소 검색',
        totalCount: '총 {count}개의 쇼핑 명소',
        hoursPrefix: '영업: ',
        defaultName: '쇼핑 명소'
      },
      leisure: {
        title: '레포츠',
        subtitle: '대전에서 즐기는 레저와 스포츠'
      },
      parking: {
        title: '대전 주차장 안내',
        subtitle: '대전의 주차장 정보를 확인하세요',
        offStreet: '노외주차장',
        onStreet: '노상주차장',
        public: '공영',
        private: '민영',
        publicParking: '공영 주차장',
        privateParking: '민영 주차장',
        filteredResults: '필터 결과',
        parkingOnPage: '이 페이지 주차장',
        loading: '주차장 정보를 불러오는 중...',
        noInfo: '주차장 정보가 없습니다.',
        parkingLot: '주차장',
        capacity: '주차 면수',
        spots: '면',
        weekday: '평일',
        free: '무료',
        basic: '기본',
        additional: '추가',
        payment: '결제',
        checkInfo: '개 주차장 정보를 확인하세요.'
      },
      map: {
        title: '지도',
        subtitle: '대전 지역 정보를 지도에서 확인하세요',
        district: '지역',
        area: '동',
        loadingMap: '지도를 불러오는 중...',
        showList: '목록 보기',
        spotsAvailable: '대 주차 가능'
      },
      search: {
        title: '통합 검색',
        subtitle: '대전의 다양한 정보를 검색하세요',
        results: '건',
        attractions: '관광지',
        restaurants: '맛집',
        events: '공연/행사',
        all: '전체',
        searching: '검색 중...',
        searchResults: '검색 결과',
        searchButton: '검색',
        placeholder: '관광지, 맛집, 공연 검색...',
        popularSearches: '인기 검색어',
        seeMoreAttractions: '관광지 더보기',
        seeMoreRestaurants: '맛집 더보기',
        seeMoreEvents: '공연/행사 더보기',
        noResults: '검색 결과가 없습니다',
        noResultsHint: '다른 검색어로 다시 시도해보세요.',
        enterSearchTerm: '검색어를 입력해주세요',
        searchDescription: '대전의 관광지, 맛집, 공연/행사를 검색해보세요.',
        suggestions: '추천 검색어:'
      },
      sharedTrips: {
        title: '여행코스',
        subtitle: '다른 여행자들의 대전 여행 코스를 둘러보세요',
        dayTrip: '당일치기',
        latest: '최신순',
        popular: '인기순',
        mostLiked: '좋아요순',
        searchPlaceholder: '코스 검색...',
        loadingCourses: '여행코스 불러오는 중...',
        recommended: '추천 여행코스',
        userCourses: '여행자 코스',
        noTrips: '등록된 여행코스가 없습니다'
      },
      myTrip: {
        title: '나만의 여행',
        subtitle: '나만의 대전 여행 코스를 만들어보세요'
      }
    },

    // 공통 UI 텍스트
    ui: {
      // 버튼/액션
      search: '검색',
      cancel: '취소',
      save: '저장',
      add: '추가하기',
      edit: '수정',
      delete: '삭제',
      close: '닫기',
      prev: '이전',
      next: '다음',
      back: '뒤로',
      refresh: '새로고침',
      copy: '복사',
      share: '공유',
      publish: '게시',
      navigate: '길찾기',
      directions: '길찾기',
      viewDetails: '자세히 보기',
      viewMore: '더보기',
      expand: '확대',
      minimize: '축소',
      bookNow: '예약하기',
      website: '홈페이지',
      create: '생성하기',
      set: '설정',
      confirmDelete: '삭제하시겠습니까?',
      deleted: '삭제되었습니다',
      loading: '로딩중...',
      remove: '제거',

      // 정렬
      sortByName: '가나다순',
      sortByViews: '조회수순',
      sortByLatest: '최신순',
      sortByPopular: '인기순',
      sortByLikes: '좋아요순',

      // 상태/정보
      loading: '로딩중',
      error: '오류',
      noData: '데이터가 없습니다',
      free: '무료',
      paid: '유료',
      noInfo: '정보없음',
      anonymous: '익명',
      recommended: '추천',

      // 접근성
      menu: '메뉴',
      searchLabel: '검색',
      previousSlide: '이전',
      nextSlide: '다음',

      // 인증
      login: '로그인',
      logout: '로그아웃',
      loginRequired: '로그인이 필요합니다'
    },

    // 상세 정보 라벨
    detail: {
      address: '주소',
      phone: '전화',
      hours: '운영시간',
      closed: '휴무일',
      contact: '문의처',
      fee: '이용요금',
      parking: '주차시설',
      strollerRental: '유모차대여',
      pets: '애완동물',
      creditCard: '신용카드',
      checkIn: '체크인',
      checkOut: '체크아웃',
      rooms: '객실수',
      facilities: '부대시설',
      signature: '대표메뉴',
      menu: '취급메뉴',
      takeout: '포장',
      organizer: '주최자',
      venue: '행사장소',
      playTime: '공연시간',
      reservation: '예약안내',
      duration: '관람소요시간',
      products: '판매품목',
      about: '소개',
      reviews: '리뷰',
      writeReview: '리뷰 작성',
      rating: '평점',
      copied: '복사됨',
      copyAddress: '주소복사',
      location: '위치/교통',
      usageInfo: '이용 안내',
      kakaoMap: '카카오맵',
      naverMap: '네이버지도',
      submitReview: '리뷰 등록',
      noReviews: '아직 리뷰가 없습니다. 첫 번째 리뷰를 작성해보세요!',
      firstReview: '첫 번째 리뷰를 작성해보세요!',
      urlCopied: 'URL이 복사되었습니다!',
      notFound: '정보를 찾을 수 없습니다.',
      loadFailed: '데이터를 불러오는데 실패했습니다.',
      goBack: '뒤로 가기',
      loading: '정보를 불러오는 중...',
      noImage: '이미지 없음',
      enterReview: '리뷰 내용을 입력해주세요',
      writeReviewPlaceholder: '리뷰를 작성해주세요...',
      deleteReview: '리뷰를 삭제하시겠습니까?',
      submitting: '등록 중...',
      reviewsCount: '개의 리뷰',
      addToTrip: '내 여행에 추가',
      linkCopy: '링크 복사',
      shareTo: '공유하기',
      tripSelect: '여행 선택',
      daySelect: '일차 선택',
      noTripPlans: '여행 계획이 없습니다.',
      newTripCreate: '새 여행 만들기',
      visitWebsite: '홈페이지 방문하기',
      addToTripSuccess: '여행에 추가되었습니다!',
      addToTripFailed: '추가에 실패했습니다.',
      kakaoTalk: '카카오톡'
    },

    // 교통수단
    transport: {
      walk: '도보',
      car: '자가용',
      bus: '버스',
      subway: '지하철',
      taxi: '택시',
      bicycle: '자전거',
      minutes: '분',
      stops: '정거장',
      stations: '역',
      distance: '거리',
      estimated: '예상',
      loadingTransit: '대중교통 정보 조회 중...',
      availableRoutes: '이용 가능 노선',
      line: '이용 노선',
      walkOrDrive: '도보 또는 자가용 이용',
      toPlace: '까지 이동'
    },

    // 날씨
    weather: {
      title: '대전 날씨',
      temperature: '온도',
      humidity: '습도',
      windSpeed: '풍속',
      pressure: '기압',
      dust: '미세먼지',
      refresh: '새로고침',
      expand: '펼치기',
      collapse: '접기',
      good: '좋음',
      normal: '보통',
      bad: '나쁨',
      veryBad: '매우나쁨',
      daejeon: '대전광역시'
    },

    // 여행 코스 관련
    trip: {
      days: '일',
      day: '일차',
      places: '곳',
      accommodation: '숙소',
      start: '출발',
      destination: '도착지',
      origin: '출발지',
      published: '게시됨',
      invite: '초대',
      join: '참여하기',
      leave: '나가기',
      admin: '관리자',
      viewOnly: '보기만',
      remove: '제거',
      editPermission: '편집',
      viewPermission: '보기',
      permissionNote: '참여 시 권한이 부여됩니다',
      startDate: '시작일',
      endDate: '종료일',
      create: '생성하기',
      touristSpots: '관광지',
      restaurants: '맛집',
      culture: '문화시설',
      spots: '면',
      route: '여행 경로',
      noPlaces: '이 날에는 장소가 없습니다.',
      noItinerary: '아직 일정이 없습니다.',
      memo: '메모',
      dayNumber: '일차',
      clickToViewDetails: '장소를 클릭하면 상세 정보를 볼 수 있습니다',
      createYourOwn: '나만의 여행 계획을 만들어보세요!',
      createMyTrip: '내 여행 만들기',
      createTrip: '새 여행 계획',
      tripTitle: '여행 제목',
      tripDescription: '설명 (선택)',
      numberOfDays: '여행 일수',
      stopSharing: '공유 중지',
      public: '공개',
      private: '비공개',
      saving: '여행 계획 저장 중...',
      savedSuccess: '여행이 저장되었습니다',
      saveFailed: '저장 실패',
      addPlace: '장소 추가하기',
      searchPlaces: '장소 검색...',
      enterMemo: '메모 입력',
      noTrips: '아직 여행 계획이 없습니다',
      createFirstTrip: '첫 여행 만들기',
      tripList: '내 여행 목록',
      myTripPlans: '나의 여행 계획',
      planYourTrip: '대전에서의 특별한 여행을 계획해보세요',
      editTrip: '여행 계획 수정',
      tripTitlePlaceholder: '예: 대전 봄 여행',
      tripDescPlaceholder: '여행에 대한 간단한 설명...',
      setAccommodation: '숙소 설정',
      searchAccommodation: '숙소 검색',
      searchByNameOrAddress: '숙소 이름 또는 주소 검색...',
      orEnterManually: '또는 직접 입력',
      accommodationName: '숙소 이름',
      accommodationAddress: '숙소 주소',
      accommodationNamePlaceholder: '예: 대전 호텔',
      accommodationAddressPlaceholder: '예: 대전시 중구 대종로 480',
      accommodationHint: '숙소를 설정하면 2일차부터 숙소에서 출발합니다',
      sharedWithMe: '공유받은 여행',
      selectTrip: '여행을 선택해주세요',
      selectTripHint: '왼쪽 목록에서 여행을 선택하면 상세 일정을 볼 수 있습니다',
      publishTrip: '여행 계획 게시',
      publishInfo: '게시하면 다른 사용자들이 회원님의 여행 코스를 볼 수 있습니다. 수정은 불가능하며, 읽기만 가능합니다.',
      authorNickname: '작성자 닉네임',
      nicknamePlaceholder: '닉네임 (선택사항)',
      thumbnailImage: '썸네일 이미지',
      selectImage: '이미지 선택',
      imageHint: '(JPG, PNG, GIF, WebP / 최대 10MB)',
      orEnterUrl: '또는 URL 직접 입력',
      uploading: '업로드 중...',
      inviteFriends: '같이 만들기',
      inviteInfo: '아래 링크를 친구에게 공유하면 함께 여행 계획을 편집할 수 있습니다.',
      inviteExpireInfo: '※ 초대 링크는 7일간 유효하며, 최대 10명까지 참여할 수 있습니다.',
      inviteViaKakao: '카카오톡으로 초대',
      tripInvitation: '여행 초대',
      collaborators: '함께하는 사람들',
      noCollaborators: '아직 함께하는 사람이 없습니다.',
      canEdit: '편집 가능',
      createNewInvite: '새로운 초대 링크 생성',
      createNewInviteLink: '새로운 초대 링크 생성',
      copy: '복사',
      publish: '게시하기',
      routeMap: '경로 지도',
      visitOrder: '방문 순서',
      routeLine: '이동 경로',
      mapTip: '일정을 펼치면 해당 날짜의 장소들이 지도에 표시됩니다',
      showMap: '지도 보기',
      unpublishTitle: '게시 취소',
      publishTitle: '게시하기',
      inviteTitle: '같이 만들기',
      leaveTitle: '나가기',
      deleteTrip: '이 여행 계획을 삭제하시겠습니까?',
      createTripFailed: '여행 계획 생성에 실패했습니다',
      enterTitleAndDates: '제목과 날짜를 입력해주세요',
      enterTitle: '제목을 입력해주세요',
      saved: '저장되었습니다!',
      saveFailed2: '저장에 실패했습니다',
      unpublish: '게시를 취소하시겠습니까?\n(업로드된 썸네일 이미지도 함께 삭제됩니다)',
      unpublished: '게시가 취소되었습니다.',
      tripPublished: '여행 계획이 게시되었습니다!',
      publishFailed: '게시 실패',
      errorWhilePublishing: '게시 중 오류가 발생했습니다.',
      errorOccurred: '취소 중 오류가 발생했습니다.',
      inviteLinkCopied: '초대 링크가 복사되었습니다!',
      inviteLinkFailed: '초대 링크 생성에 실패했습니다.',
      kakaoShareNotAvailable: '카카오 공유를 사용할 수 없습니다.',
      letsPlantTogether: '함께 여행 계획을 만들어요!',
      joinTrip: '여행 참여하기',
      daejeonTrip: '대전 여행',
      loginToAcceptInvite: '초대를 수락하려면 로그인이 필요합니다.',
      invalidInviteLink: '유효하지 않은 초대 링크입니다.',
      loadInviteInfoFailed: '초대 정보를 불러오는데 실패했습니다.',
      joinedTrip: '여행에 참여했습니다!',
      acceptInviteFailed: '초대 수락에 실패했습니다.',
      removeCollaborator: '정말 이 협업자를 제거하시겠습니까?',
      removeCollaboratorFailed: '협업자 제거에 실패했습니다.',
      leaveTrip: '정말 이 여행에서 나가시겠습니까?',
      leaveTripFailed: '여행 나가기에 실패했습니다.',
      enterAccommodationInfo: '숙소 이름과 주소를 입력해주세요',
      unsupportedFileType: '지원되지 않는 파일 형식입니다. (JPG, PNG, GIF, WebP만 가능)',
      fileSizeExceeds: '파일 크기가 10MB를 초과합니다.',
      imageUploadFailed: '이미지 업로드 실패',
      noPlacesYet: '아직 추가된 장소가 없습니다',
      searchAndAddPlaces: '위에서 장소를 검색하여 추가해보세요',
      addToDay: '일정 추가',
      dragToReorder: '드래그하여 순서 변경',
      about: '약',
      minutes: '분',
      won: '원',
      stops: '정거장',
      stations: '역',
      walk: '도보',
      estimate: '예상',
      orAlt: '또는',
      nearbyParking: '주변 주차장',
      searchingParking: '주차장 검색 중...',
      parkingWithin5km: '5km 이내 주차장',
      noParkingNearby: '근처에 주차장이 없습니다',
      transportMethod: '이동 방법:',
      changeTransport: '이동수단 변경',
      addTransport: '이동 방법 추가',
      noSubwayRoute: '이용 가능한 지하철 노선이 없습니다',
      noBusRoute: '이용 가능한 버스 노선이 없습니다',
      otherRoutes: '다른 경로',
      estimated: '예상 시간',
      syncingRealtime: '동기화 중...',
      realtimeSync: '실시간 동기화',
      checkingLogin: '로그인 확인 중...',
      loginRequired: '로그인이 필요합니다',
      loginWithKakaoDesc: '나만의 여행 계획을 만들려면 카카오 계정으로 로그인해주세요',
      continueWithKakao: '카카오로 시작하기',
      loginFailed: '로그인에 실패했습니다. 다시 시도해주세요.'
    },

    // 관리자
    admin: {
      dashboard: '대시보드',
      settings: '설정',
      system: '시스템',
      backToHome: '메인으로',
      email: '이메일',
      password: '비밀번호',
      table: '테이블',
      items: '개',
      rows: '행',
      thumbnail: '썸네일',
      title: '제목',
      author: '작성자',
      views: '조회수',
      likes: '좋아요',
      publishedDate: '게시일',
      actions: '관리',
      preview: '미리보기',
      active: '활성화',
      inactive: '비활성',
      order: '순서',
      link: '링크',
      diff: '차이',
      all: '전체',
      year: '년',
      month: '월',
      week: '주',
      day: '일',
      image: '이미지',
      performance: '공연명',
      type: '분류',
      status: '상태',
      price: '요금'
    }
  },

  en: {
    // Site Info
    siteName: 'To Daejeon',
    siteSubtitle: 'Let\'s Go Daejeon',
    siteDescription: 'Discover the beautiful tourist attractions, restaurants, and festivals of Daejeon.',

    // Navigation
    nav: {
      home: 'Home',
      travel: 'Attractions',
      festival: 'Festivals',
      food: 'Food',
      parking: 'Parking',
      map: 'Map',
      culture: 'Culture',
      medical: 'Medical',
      shopping: 'Shopping',
      accommodation: 'Stay'
    },

    // Quick Menu
    quickMenu: {
      title: 'Services for Your Perfect Daejeon Trip',
      subtitle: 'Explore the diverse attractions of Daejeon by category',
      travelCourse: 'Travel Course',
      restaurant: 'Restaurants',
      festival: 'Festivals',
      leisure: 'Leisure',
      seasonTravel: 'Seasonal',
      recommend: 'Recommended'
    },

    // Hero Section
    hero: {
      slide1: {
        title: 'Spring in Daejeon',
        subtitle: 'Experience the cherry blossoms in full bloom',
        description: 'Flower festivals at Yuseong Spa and Hanbat Arboretum'
      },
      slide2: {
        title: 'City of Science',
        subtitle: 'Korea\'s Science Capital',
        description: 'Meet the future at National Science Museum and Expo Science Park'
      },
      slide3: {
        title: 'Taste of Daejeon',
        subtitle: 'Discover hidden culinary gems',
        description: 'Sungsimdang, Dubu-duruchigi... Unique flavors of Daejeon'
      },
      viewMore: 'Learn More'
    },

    // Popular Spots
    popularSpots: {
      title: 'Popular Attractions in Daejeon',
      subtitle: 'Discover the most visited destinations',
      viewMore: 'View More Attractions'
    },

    // Travel Course
    travelCourse: {
      title: 'Recommended Travel Courses',
      subtitle: 'Enjoy themed tours in Daejeon',
      viewCourse: 'View Course'
    },

    // Festival Section
    festivalSection: {
      title: 'Festivals & Events',
      subtitle: 'Experience the colorful festivals of Daejeon',
      viewAll: 'View All Festivals',
      upcoming: 'Upcoming'
    },

    // Food Section
    foodSection: {
      title: 'Recommended Restaurants',
      subtitle: 'Taste the special cuisine only found in Daejeon',
      viewMore: 'View More Restaurants'
    },

    // Footer
    footer: {
      description: 'Discover the beautiful tourist attractions, restaurants, and festivals of Daejeon.',
      tourInfo: 'Tourism Info',
      customerService: 'Customer Service',
      relatedSites: 'Related Sites',
      faq: 'FAQ',
      tourOffice: 'Tourist Office',
      travelGuide: 'Travel Guide',
      daejeonCity: 'Daejeon City',
      visitKorea: 'Visit Korea',
      tourCorp: 'Daejeon Tourism',
      copyright: '© 2026 To Daejeon. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
      copyrightPolicy: 'Copyright Policy',
      tourHotline: 'Tour Hotline 1577-3025',
      dataSource: 'Tourism data provided by Daejeon Metropolitan City Open Data Portal and Korea Tourism Organization Tour API.',
      disclaimer: 'This site is not the official website of Daejeon Metropolitan City. It is a private website operated to provide tourism information.'
    },

    // Common
    common: {
      viewDetails: 'View Details',
      category: 'Category',
      all: 'All',
      total: 'Total',
      count: '',
      hours: 'hours',
      location: 'Location',
      period: 'Period',
      search: 'Search',
      allDong: 'All Areas',
      attractions: 'attractions',
      restaurants: 'restaurants',
      addedToTrip: 'Added to your trip!',
      addFailed: 'Failed to add.',
      errorOccurred: 'An error occurred.',
      syncRequired: 'Please sync TourAPI data from admin page first.',
      loadFailed: 'Failed to load data.',
      loadingAttractions: 'Loading attractions...',
      loadingRestaurants: 'Loading restaurants...',
      loadingFestivals: 'Loading festivals...',
      loadingData: 'Loading data...',
      visitWebsite: 'Visit Website',
      addToTrip: 'Add to Trip',
      noImage: 'No Image',
      noDescription: 'No description available.',
      noResults: 'No results found.',
      noTrips: 'No saved trips.',
      createTrip: 'Create New Trip',
      selectTrip: 'Select a trip',
      selectDay: 'Select a day',
      photoBy: 'Photo: ',
      sourceBy: 'Source: ',
      photoByKTO: 'Photos by: Korea Tourism Organization',
      linkCopied: 'Link copied!',
      loadingTrip: 'Loading trip plan...',
      tripNotFound: 'Trip plan not found.',
      backToHome: 'Back to Home',
      loadingDetails: 'Loading details...',
      getDirections: 'Get Directions',
      noDaysInTrip: 'No days in the selected trip.',
      addDaysHint: 'Please add days in the "My Trip" page first.',
      dayFormat: 'Day {n}',
      navigate: 'Navigate',
      retry: 'Retry',
      noAddress: 'No address'
    },

    // Categories
    categories: {
      all: 'All',
      nature: 'Nature/Parks',
      science: 'Science/Culture',
      spa: 'Spa/Hot Springs',
      history: 'History/Heritage',
      experience: 'Experience/Activities',
      korean: 'Korean',
      bakery: 'Bakery',
      cafe: 'Cafe',
      western: 'Western',
      culture: 'Culture/Science',
      tradition: 'Culture/Traditional',
      food: 'Food',
      sports: 'Sports/Health'
    },

    // Page Titles
    pages: {
      travel: {
        title: 'Daejeon Attractions',
        subtitle: 'Discover the diverse charms of Daejeon, the city of science',
        spots: 'attractions'
      },
      festival: {
        title: 'Daejeon Festivals & Events',
        subtitle: 'Experience the colorful festivals and events in Daejeon',
        festivals: 'Festivals',
        performances: 'Performances',
        loadingEvents: 'Loading events...',
        theme: 'Theme',
        place: 'Place',
        events: 'events',
        noEvents: 'No events are currently available.',
        organizedBy: 'Organized by'
      },
      food: {
        title: 'Daejeon Restaurants',
        subtitle: 'Discover the special cuisine only found in Daejeon',
        restaurants: 'restaurants'
      },
      medical: {
        title: 'Medical Facilities',
        subtitle: 'Find hospitals, clinics, and pharmacies in Daejeon',
        hospital: 'Hospital',
        clinic: 'Clinic',
        pharmacy: 'Pharmacy'
      },
      accommodation: {
        title: 'Accommodation',
        subtitle: 'Enjoy a comfortable stay in Daejeon',
        hotel: 'Hotel',
        motel: 'Motel',
        pension: 'Pension',
        guesthouse: 'Guesthouse'
      },
      culture: {
        title: 'Cultural Facilities',
        subtitle: 'Experience culture and arts in Daejeon',
        museum: 'Museum',
        library: 'Library',
        theater: 'Theater',
        gallery: 'Gallery'
      },
      shopping: {
        title: 'Shopping',
        subtitle: 'Explore shopping spots in Daejeon',
        loading: 'Loading shopping places...',
        noResults: 'No shopping places found.',
        searchPlaceholder: 'Search shopping places',
        totalCount: 'Total {count} shopping places',
        hoursPrefix: 'Hours: ',
        defaultName: 'Shopping Place'
      },
      leisure: {
        title: 'Leisure & Sports',
        subtitle: 'Enjoy leisure and sports activities in Daejeon',
        loading: 'Loading leisure spots...',
        sortByName: 'Name',
        sortByViews: 'Views',
        closed: 'Closed',
        directions: 'Directions'
      },
      parking: {
        title: 'Daejeon Parking Guide',
        subtitle: 'Find parking information in Daejeon',
        offStreet: 'Off-street Parking',
        onStreet: 'On-street Parking',
        public: 'Public',
        private: 'Private',
        publicParking: 'Public Parking',
        privateParking: 'Private Parking',
        filteredResults: 'Filtered Results',
        parkingOnPage: 'Parking on this page',
        loading: 'Loading parking information...',
        noInfo: 'No parking information available.',
        parkingLot: 'Parking Lot',
        capacity: 'Capacity',
        spots: ' spots',
        weekday: 'Weekday',
        free: 'Free',
        basic: 'Basic',
        additional: 'Add',
        payment: 'Payment',
        checkInfo: ' parking lots in Daejeon.'
      },
      map: {
        title: 'Map',
        subtitle: 'Explore Daejeon on the map',
        district: 'District',
        area: 'Area',
        loadingMap: 'Loading map...',
        showList: 'Show List',
        spotsAvailable: ' spots available'
      },
      search: {
        title: 'Search',
        subtitle: 'Search for various information in Daejeon',
        results: ' results',
        attractions: 'Attractions',
        restaurants: 'Restaurants',
        events: 'Performances/Events',
        all: 'All',
        searching: 'Searching...',
        searchResults: 'search results',
        searchButton: 'Search',
        placeholder: 'Search attractions, restaurants, events...',
        popularSearches: 'Popular Searches',
        seeMoreAttractions: 'See more attractions',
        seeMoreRestaurants: 'See more restaurants',
        seeMoreEvents: 'See more events',
        noResults: 'No results found',
        noResultsHint: 'Try searching with different keywords.',
        enterSearchTerm: 'Enter your search term',
        searchDescription: 'Search for attractions, restaurants, and events in Daejeon.',
        suggestions: 'Suggestions:'
      },
      sharedTrips: {
        title: 'Travel Courses',
        subtitle: 'Browse travel courses from other travelers',
        dayTrip: 'Day Trip',
        latest: 'Latest',
        popular: 'Popular',
        mostLiked: 'Most Liked',
        searchPlaceholder: 'Search courses...',
        loadingCourses: 'Loading travel courses...',
        recommended: 'Recommended Courses',
        userCourses: 'User Courses',
        noTrips: 'No travel courses found'
      },
      myTrip: {
        title: 'My Trip',
        subtitle: 'Create your own Daejeon travel course'
      }
    },

    // Common UI Text
    ui: {
      // Buttons/Actions
      search: 'Search',
      cancel: 'Cancel',
      save: 'Save',
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      close: 'Close',
      prev: 'Prev',
      next: 'Next',
      back: 'Back',
      refresh: 'Refresh',
      copy: 'Copy',
      share: 'Share',
      publish: 'Publish',
      navigate: 'Navigate',
      directions: 'Directions',
      viewDetails: 'View Details',
      viewMore: 'More',
      expand: 'Expand',
      minimize: 'Minimize',
      bookNow: 'Book Now',
      website: 'Website',
      create: 'Create',
      set: 'Set',
      confirmDelete: 'Are you sure you want to delete?',
      deleted: 'Deleted',
      loading: 'Loading...',
      remove: 'Remove',

      // Sorting
      sortByName: 'Name',
      sortByViews: 'Views',
      sortByLatest: 'Latest',
      sortByPopular: 'Popular',
      sortByLikes: 'Most Liked',

      // Status/Info
      loading: 'Loading',
      error: 'Error',
      noData: 'No data available',
      free: 'Free',
      paid: 'Paid',
      noInfo: 'No info',
      anonymous: 'Anonymous',
      recommended: 'Recommended',

      // Accessibility
      menu: 'Menu',
      searchLabel: 'Search',
      previousSlide: 'Previous',
      nextSlide: 'Next',

      // Authentication
      login: 'Login',
      logout: 'Logout',
      loginRequired: 'Login required'
    },

    // Detail Labels
    detail: {
      address: 'Address',
      phone: 'Phone',
      hours: 'Hours',
      closed: 'Closed',
      contact: 'Contact',
      fee: 'Fee',
      parking: 'Parking',
      strollerRental: 'Stroller Rental',
      pets: 'Pets',
      creditCard: 'Credit Card',
      checkIn: 'Check-in',
      checkOut: 'Check-out',
      rooms: 'Rooms',
      facilities: 'Facilities',
      signature: 'Signature',
      menu: 'Menu',
      takeout: 'Takeout',
      organizer: 'Organizer',
      venue: 'Venue',
      playTime: 'Play Time',
      reservation: 'Reservation',
      duration: 'Duration',
      products: 'Products',
      about: 'About',
      reviews: 'Reviews',
      writeReview: 'Write Review',
      rating: 'Rating',
      copied: 'Copied',
      copyAddress: 'Copy Address',
      location: 'Location',
      usageInfo: 'Information',
      kakaoMap: 'Kakao Map',
      naverMap: 'Naver Map',
      submitReview: 'Submit Review',
      noReviews: 'No reviews yet. Be the first to write a review!',
      firstReview: 'Be the first to write a review!',
      urlCopied: 'URL copied!',
      notFound: 'Information not found.',
      loadFailed: 'Failed to load data.',
      goBack: 'Go Back',
      loading: 'Loading...',
      noImage: 'No Image',
      enterReview: 'Please enter review content',
      writeReviewPlaceholder: 'Write your review...',
      deleteReview: 'Delete this review?',
      submitting: 'Submitting...',
      reviewsCount: ' reviews',
      addToTrip: 'Add to Trip',
      linkCopy: 'Copy Link',
      shareTo: 'Share',
      tripSelect: 'Select Trip',
      daySelect: 'Select Day',
      noTripPlans: 'No trip plans yet.',
      newTripCreate: 'Create New Trip',
      visitWebsite: 'Visit Website',
      addToTripSuccess: 'Added to your trip!',
      addToTripFailed: 'Failed to add.',
      kakaoTalk: 'KakaoTalk'
    },

    // Transportation
    transport: {
      walk: 'Walk',
      car: 'Car',
      bus: 'Bus',
      subway: 'Subway',
      taxi: 'Taxi',
      bicycle: 'Bicycle',
      minutes: 'min',
      stops: 'stops',
      stations: 'stations',
      distance: 'Distance',
      estimated: 'estimated',
      loadingTransit: 'Loading transit info...',
      availableRoutes: 'Available routes',
      line: 'Line',
      walkOrDrive: 'Walk or drive',
      toPlace: 'to'
    },

    // Weather
    weather: {
      title: 'Daejeon Weather',
      temperature: 'Temperature',
      humidity: 'Humidity',
      windSpeed: 'Wind Speed',
      pressure: 'Pressure',
      dust: 'Fine Dust',
      refresh: 'Refresh',
      expand: 'Expand',
      collapse: 'Collapse',
      good: 'Good',
      normal: 'Normal',
      bad: 'Bad',
      veryBad: 'Very Bad',
      daejeon: 'Daejeon'
    },

    // Trip Related
    trip: {
      days: ' days',
      day: '',
      places: ' places',
      accommodation: 'Accommodation',
      start: 'Start',
      destination: 'Destination',
      origin: 'Origin',
      published: 'Published',
      invite: 'Invite',
      join: 'Join',
      leave: 'Leave',
      admin: 'Admin',
      viewOnly: 'View only',
      remove: 'Remove',
      editPermission: 'Edit',
      viewPermission: 'View',
      permissionNote: 'Permission will be granted upon joining',
      startDate: 'Start Date',
      endDate: 'End Date',
      create: 'Create',
      touristSpots: 'Tourist Spots',
      restaurants: 'Restaurants',
      culture: 'Culture',
      spots: ' spots',
      route: 'Trip Route',
      noPlaces: 'No places for this day.',
      noItinerary: 'No itinerary yet.',
      memo: 'Note',
      dayNumber: 'Day',
      clickToViewDetails: 'Click a place to view details',
      createYourOwn: 'Create your own travel plan!',
      createMyTrip: 'Create My Trip',
      createTrip: 'New Trip',
      tripTitle: 'Trip Title',
      tripDescription: 'Description (optional)',
      numberOfDays: 'Number of Days',
      stopSharing: 'Stop Sharing',
      public: 'Public',
      private: 'Private',
      saving: 'Saving trip plan...',
      savedSuccess: 'Trip saved successfully',
      saveFailed: 'Save failed',
      addPlace: 'Add Places',
      searchPlaces: 'Search places...',
      enterMemo: 'Enter memo',
      noTrips: 'No trip plans yet',
      createFirstTrip: 'Create First Trip',
      tripList: 'My Trips',
      myTripPlans: 'My Trip Plans',
      planYourTrip: 'Plan your special trip in Daejeon',
      editTrip: 'Edit Trip',
      tripTitlePlaceholder: 'e.g., Spring Trip to Daejeon',
      tripDescPlaceholder: 'Brief description of your trip...',
      setAccommodation: 'Set Accommodation',
      searchAccommodation: 'Search Accommodation',
      searchByNameOrAddress: 'Search by name or address...',
      orEnterManually: 'or enter manually',
      accommodationName: 'Accommodation Name',
      accommodationAddress: 'Address',
      accommodationNamePlaceholder: 'e.g., Daejeon Hotel',
      accommodationAddressPlaceholder: 'e.g., 480 Daejong-ro, Jung-gu, Daejeon',
      accommodationHint: 'Set accommodation to start from hotel on Day 2+',
      sharedWithMe: 'Shared with me',
      selectTrip: 'Select a trip',
      selectTripHint: 'Select a trip from the list to view details',
      publishTrip: 'Publish Trip Plan',
      publishInfo: 'Once published, other users can view your trip plan. They can only read, not edit.',
      authorNickname: 'Author Nickname',
      nicknamePlaceholder: 'Nickname (optional)',
      thumbnailImage: 'Thumbnail Image',
      selectImage: 'Select Image',
      imageHint: '(JPG, PNG, GIF, WebP / Max 10MB)',
      orEnterUrl: 'Or enter URL directly',
      uploading: 'Uploading...',
      inviteFriends: 'Invite Friends',
      inviteInfo: 'Share this link with friends to plan the trip together.',
      inviteExpireInfo: '※ The invite link is valid for 7 days and can be used by up to 10 people.',
      inviteViaKakao: 'Invite via KakaoTalk',
      tripInvitation: 'Trip Invitation',
      collaborators: 'Collaborators',
      noCollaborators: 'No collaborators yet.',
      canEdit: 'Can edit',
      createNewInvite: 'Create New Invite Link',
      createNewInviteLink: 'Create New Invite Link',
      copy: 'Copy',
      publish: 'Publish',
      routeMap: 'Route Map',
      visitOrder: 'Visit Order',
      routeLine: 'Route',
      mapTip: 'Expand a day to see its places on the map',
      showMap: 'Show Map',
      unpublishTitle: 'Unpublish',
      publishTitle: 'Publish',
      inviteTitle: 'Invite',
      leaveTitle: 'Leave',
      deleteTrip: 'Delete this trip plan?',
      createTripFailed: 'Failed to create trip plan',
      enterTitleAndDates: 'Please enter title and dates',
      enterTitle: 'Please enter a title',
      saved: 'Saved!',
      saveFailed2: 'Failed to save',
      unpublish: 'Unpublish this trip?\n(Uploaded thumbnail image will also be deleted)',
      unpublished: 'Unpublished.',
      tripPublished: 'Trip plan published!',
      publishFailed: 'Publish failed',
      errorWhilePublishing: 'Error occurred while publishing.',
      errorOccurred: 'Error occurred.',
      inviteLinkCopied: 'Invite link copied!',
      inviteLinkFailed: 'Failed to create invite link.',
      kakaoShareNotAvailable: 'Kakao share is not available.',
      letsPlantTogether: 'Let\'s plan a trip together!',
      joinTrip: 'Join Trip',
      daejeonTrip: 'Daejeon Trip',
      loginToAcceptInvite: 'Please login to accept the invitation.',
      invalidInviteLink: 'Invalid invite link.',
      loadInviteInfoFailed: 'Failed to load invite info.',
      joinedTrip: 'trip joined!',
      acceptInviteFailed: 'Failed to accept invitation.',
      removeCollaborator: 'Are you sure you want to remove this collaborator?',
      removeCollaboratorFailed: 'Failed to remove collaborator.',
      leaveTrip: 'Are you sure you want to leave this trip?',
      leaveTripFailed: 'Failed to leave trip.',
      enterAccommodationInfo: 'Please enter accommodation name and address',
      unsupportedFileType: 'Unsupported file type. (JPG, PNG, GIF, WebP only)',
      fileSizeExceeds: 'File size exceeds 10MB.',
      imageUploadFailed: 'Image upload failed',
      noPlacesYet: 'No places added yet',
      searchAndAddPlaces: 'Search and add places above',
      addToDay: 'Add to Day',
      dragToReorder: 'Drag to reorder',
      about: 'about',
      minutes: 'min',
      won: '₩',
      stops: 'stops',
      stations: 'stations',
      walk: 'Walk',
      estimate: 'estimated',
      orAlt: 'or',
      nearbyParking: 'Nearby Parking',
      searchingParking: 'Searching parking...',
      parkingWithin5km: 'Parking within 5km',
      noParkingNearby: 'No parking nearby',
      transportMethod: 'Transport:',
      changeTransport: 'Change transport',
      addTransport: 'Add transport',
      noSubwayRoute: 'No subway route available',
      noBusRoute: 'No bus route available',
      otherRoutes: 'Other routes',
      estimated: 'estimated',
      syncingRealtime: 'Syncing...',
      realtimeSync: 'Real-time sync',
      checkingLogin: 'Checking login status...',
      loginRequired: 'Login Required',
      loginWithKakaoDesc: 'Please login with Kakao to create your trip plans',
      continueWithKakao: 'Continue with Kakao',
      loginFailed: 'Login failed. Please try again.'
    },

    // Admin
    admin: {
      dashboard: 'Dashboard',
      settings: 'Settings',
      system: 'System',
      backToHome: 'Back to Home',
      email: 'Email',
      password: 'Password',
      table: 'Table',
      items: 'items',
      rows: 'rows',
      thumbnail: 'Thumbnail',
      title: 'Title',
      author: 'Author',
      views: 'Views',
      likes: 'Likes',
      publishedDate: 'Published',
      actions: 'Actions',
      preview: 'Preview',
      active: 'Active',
      inactive: 'Inactive',
      order: 'Order',
      link: 'Link',
      diff: 'Diff',
      all: 'All',
      year: 'Year',
      month: 'Month',
      week: 'Week',
      day: 'Day',
      image: 'Image',
      performance: 'Performance',
      type: 'Type',
      status: 'Status',
      price: 'Price'
    }
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language')
    return saved || 'ko'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
  }, [language])

  const t = translations[language]

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ko' ? 'en' : 'ko')
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
